/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type OpenRole = {
  _type: "openRole";
  title?: string;
  description?: string;
  experienceLevel?: "any" | "beginner" | "intermediate" | "advanced";
  learningOutcome?: string;
};

export type EventLocation = {
  _type: "eventLocation";
  locationType?: "inPerson" | "online" | "hybrid";
  place?: string;
  onlineUrl?: string;
  directions?: string;
};

export type SocialLink = {
  _type: "socialLink";
  platform?:
    | "discord"
    | "github"
    | "instagram"
    | "linkedin"
    | "youtube"
    | "teams"
    | "other";
  label?: string;
  url?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  shareImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type PersonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "person";
};

export type OfficerRole = {
  _id: string;
  _type: "officerRole";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  person?: PersonReference;
  position?: string;
  term?: string;
  isCurrent?: boolean;
  displayOrder?: number;
};

export type Opportunity = {
  _id: string;
  _type: "opportunity";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  organization?: string;
  opportunityType?:
    | "internship"
    | "fullTime"
    | "hackathon"
    | "research"
    | "scholarship"
    | "competition"
    | "campus";
  description?: string;
  location?: string;
  workArrangement?: "onSite" | "hybrid" | "remote";
  applicationUrl?: string;
  deadline?: string;
  postedAt?: string;
  skills?: Array<string>;
  majors?: Array<string>;
  featured?: boolean;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type EventReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "event";
};

export type ResourceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "resource";
};

export type Resource = {
  _id: string;
  _type: "resource";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  resourceType?:
    | "workshop"
    | "slides"
    | "guide"
    | "cheatSheet"
    | "repository"
    | "recording"
    | "tutorial"
    | "interviewPrep"
    | "career";
  description?: string;
  topics?: Array<string>;
  experienceLevel?: "any" | "beginner" | "intermediate" | "advanced";
  featured?: boolean;
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  externalUrl?: string;
  githubUrl?: string;
  author?: PersonReference;
  event?: EventReference;
  relatedResources?: Array<
    {
      _key: string;
    } & ResourceReference
  >;
  publishedAt?: string;
  updatedAt?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  status?:
    "idea" | "recruiting" | "active" | "testing" | "shipped" | "archived";
  shortDescription?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  screenshots?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  techStack?: Array<string>;
  featured?: boolean;
  experienceLevel?: "any" | "beginner" | "intermediate" | "advanced";
  noExperienceRequired?: boolean;
  lead?: PersonReference;
  mentors?: Array<
    {
      _key: string;
    } & PersonReference
  >;
  contributors?: Array<
    {
      _key: string;
    } & PersonReference
  >;
  openRoles?: Array<
    {
      _key: string;
    } & OpenRole
  >;
  learningOutcomes?: Array<string>;
  githubUrl?: string;
  demoUrl?: string;
  discussionUrl?: string;
  currentFocus?: string;
  latestMilestone?: string;
  startedAt?: string;
  completedAt?: string;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  status?: "scheduled" | "completed" | "cancelled";
  eventType?:
    | "workshop"
    | "meeting"
    | "speaker"
    | "hackathon"
    | "studySession"
    | "career"
    | "social";
  startsAt?: string;
  endsAt?: string;
  location?: EventLocation;
  summary?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  presenters?: Array<
    {
      _key: string;
    } & PersonReference
  >;
  topics?: Array<string>;
  featured?: boolean;
  experienceLevel?: "any" | "beginner" | "intermediate" | "advanced";
  noExperienceRequired?: boolean;
  prerequisites?: Array<string>;
  setupInstructions?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  registrationUrl?: string;
  communityUrl?: string;
  recap?: string;
  relatedResources?: Array<
    {
      _key: string;
    } & ResourceReference
  >;
  seo?: Seo;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  clubName?: string;
  shortName?: string;
  description?: string;
  meetingInfo?: string;
  facultyAdvisor?: PersonReference;
  footerNote?: string;
  contactEmail?: string;
  discordUrl?: string;
  githubUrl?: string;
  teamsUrl?: string;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  seo?: Seo;
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  shortBio?: string;
  email?: string;
  githubUrl?: string;
  linkedinUrl?: string;
  websiteUrl?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | OpenRole
  | EventLocation
  | SocialLink
  | SanityImageAssetReference
  | Seo
  | PersonReference
  | OfficerRole
  | Opportunity
  | SanityFileAssetReference
  | EventReference
  | ResourceReference
  | Resource
  | Slug
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | Event
  | SiteSettings
  | Person
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries/admin.ts
// Variable: ADMIN_DASHBOARD_STATS_QUERY
// Query: {  "upcomingEvents": count(*[_type == "event" && status == "scheduled"    && dateTime(coalesce(endsAt, startsAt)) >= dateTime(now())]),  "pastEvents": count(*[_type == "event"    && dateTime(coalesce(endsAt, startsAt)) < dateTime(now())]),  "activeProjects": count(*[_type == "project" && status in ["recruiting", "active", "testing"]]),  "recruitingProjects": count(*[_type == "project" && status == "recruiting"]),  "openOpportunities": count(*[_type == "opportunity"    && (!defined(deadline) || dateTime(deadline + "T23:59:59Z") >= dateTime(now()))]),  "publishedResources": count(*[_type == "resource"]),  "people": count(*[_type == "person"])}
export type ADMIN_DASHBOARD_STATS_QUERY_RESULT = {
  upcomingEvents: number;
  pastEvents: number;
  activeProjects: number;
  recruitingProjects: number;
  openOpportunities: number;
  publishedResources: number;
  people: number;
};

// Source: src/sanity/queries/admin.ts
// Variable: ADMIN_UPCOMING_EVENTS_QUERY
// Query: *[_type == "event" && status == "scheduled"    && dateTime(coalesce(endsAt, startsAt)) >= dateTime(now())]    | order(startsAt asc)[0...5]{      _id,      title,      startsAt,      endsAt,      eventType,      location    }
export type ADMIN_UPCOMING_EVENTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  startsAt: string | null;
  endsAt: string | null;
  eventType:
    | "career"
    | "hackathon"
    | "meeting"
    | "social"
    | "speaker"
    | "studySession"
    | "workshop"
    | null;
  location: EventLocation | null;
}>;

// Source: src/sanity/queries/admin.ts
// Variable: ADMIN_NEEDS_ATTENTION_QUERY
// Query: {  "eventsMissingSummary": *[_type == "event" && status == "scheduled"    && dateTime(coalesce(endsAt, startsAt)) >= dateTime(now())    && !defined(summary)]{ _id, title, startsAt },  "eventsMissingLocation": *[_type == "event" && status == "scheduled"    && dateTime(coalesce(endsAt, startsAt)) >= dateTime(now())    && !defined(location.locationType)]{ _id, title, startsAt },  "eventsToClose": *[_type == "event" && status == "scheduled"    && dateTime(coalesce(endsAt, startsAt)) < dateTime(now())]    | order(startsAt desc)[0...5]{ _id, title, startsAt },  "opportunitiesClosingSoon": *[_type == "opportunity" && defined(deadline)    && dateTime(deadline + "T23:59:59Z") >= dateTime(now())    && dateTime(deadline + "T23:59:59Z") <= dateTime(now()) + 60 * 60 * 24 * 7]    | order(deadline asc){ _id, title, organization, deadline }}
export type ADMIN_NEEDS_ATTENTION_QUERY_RESULT = {
  eventsMissingSummary: Array<{
    _id: string;
    title: string | null;
    startsAt: string | null;
  }>;
  eventsMissingLocation: Array<{
    _id: string;
    title: string | null;
    startsAt: string | null;
  }>;
  eventsToClose: Array<{
    _id: string;
    title: string | null;
    startsAt: string | null;
  }>;
  opportunitiesClosingSoon: Array<{
    _id: string;
    title: string | null;
    organization: string | null;
    deadline: string | null;
  }>;
};

// Source: src/sanity/queries/admin.ts
// Variable: ADMIN_EVENTS_QUERY
// Query: *[_type == "event"] | order(startsAt desc){    _id,    title,    "slug": slug.current,    status,    eventType,    startsAt,    endsAt,    featured,    location,    "isPast": dateTime(coalesce(endsAt, startsAt)) < dateTime(now()),    "resourceCount": count(*[_type == "resource" && event._ref == ^._id]),    // count() on a missing array is null, so coalesce for a plain number.    "presenterCount": coalesce(count(presenters), 0)  }
export type ADMIN_EVENTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  status: "cancelled" | "completed" | "scheduled" | null;
  eventType:
    | "career"
    | "hackathon"
    | "meeting"
    | "social"
    | "speaker"
    | "studySession"
    | "workshop"
    | null;
  startsAt: string | null;
  endsAt: string | null;
  featured: boolean | null;
  location: EventLocation | null;
  isPast: boolean | null;
  resourceCount: number;
  presenterCount: number | 0;
}>;

// Source: src/sanity/queries/admin.ts
// Variable: ADMIN_EVENT_BY_ID_QUERY
// Query: *[_type == "event" && _id == $id][0]{    _id,    title,    "slug": slug.current,    status,    eventType,    startsAt,    endsAt,    location,    summary,    experienceLevel,    noExperienceRequired,    prerequisites,    topics,    registrationUrl,    communityUrl,    recap,    featured,    "presenterIds": presenters[]._ref,    "referenceCount": count(*[references(^._id)])  }
export type ADMIN_EVENT_BY_ID_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  status: "cancelled" | "completed" | "scheduled" | null;
  eventType:
    | "career"
    | "hackathon"
    | "meeting"
    | "social"
    | "speaker"
    | "studySession"
    | "workshop"
    | null;
  startsAt: string | null;
  endsAt: string | null;
  location: EventLocation | null;
  summary: string | null;
  experienceLevel: "advanced" | "any" | "beginner" | "intermediate" | null;
  noExperienceRequired: boolean | null;
  prerequisites: Array<string> | null;
  topics: Array<string> | null;
  registrationUrl: string | null;
  communityUrl: string | null;
  recap: string | null;
  featured: boolean | null;
  presenterIds: Array<string> | null;
  referenceCount: number;
} | null;

// Source: src/sanity/queries/admin.ts
// Variable: EVENT_SLUGS_IN_USE_QUERY
// Query: *[_type == "event" && defined(slug.current) && _id != $excludeId].slug.current
export type EVENT_SLUGS_IN_USE_QUERY_RESULT = Array<string | null>;

// Source: src/sanity/queries/admin.ts
// Variable: ADMIN_PEOPLE_OPTIONS_QUERY
// Query: *[_type == "person"] | order(name asc){ _id, name }
export type ADMIN_PEOPLE_OPTIONS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
}>;

// Source: src/sanity/queries/events.ts
// Variable: UPCOMING_EVENTS_QUERY
// Query: *[_type == "event" && status != "cancelled" && dateTime(coalesce(endsAt, startsAt)) >= dateTime(now())]    | order(startsAt asc){        _id,  title,  "slug": slug.current,  status,  eventType,  startsAt,  endsAt,  summary,  featured,  experienceLevel,  noExperienceRequired,  location,      topics,      presenters[]->{ _id, name }    }
export type UPCOMING_EVENTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  status: "cancelled" | "completed" | "scheduled" | null;
  eventType:
    | "career"
    | "hackathon"
    | "meeting"
    | "social"
    | "speaker"
    | "studySession"
    | "workshop"
    | null;
  startsAt: string | null;
  endsAt: string | null;
  summary: string | null;
  featured: boolean | null;
  experienceLevel: "advanced" | "any" | "beginner" | "intermediate" | null;
  noExperienceRequired: boolean | null;
  location: EventLocation | null;
  topics: Array<string> | null;
  presenters: Array<{
    _id: string;
    name: string | null;
  }> | null;
}>;

// Source: src/sanity/queries/events.ts
// Variable: PAST_EVENTS_QUERY
// Query: *[_type == "event" && status != "cancelled"    && dateTime(coalesce(endsAt, startsAt)) < dateTime(now())]    | order(startsAt desc){        _id,  title,  "slug": slug.current,  status,  eventType,  startsAt,  endsAt,  summary,  featured,  experienceLevel,  noExperienceRequired,  location,      topics,      presenters[]->{ _id, name },      "resourceCount": count(*[_type == "resource" && event._ref == ^._id])    }
export type PAST_EVENTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  status: "cancelled" | "completed" | "scheduled" | null;
  eventType:
    | "career"
    | "hackathon"
    | "meeting"
    | "social"
    | "speaker"
    | "studySession"
    | "workshop"
    | null;
  startsAt: string | null;
  endsAt: string | null;
  summary: string | null;
  featured: boolean | null;
  experienceLevel: "advanced" | "any" | "beginner" | "intermediate" | null;
  noExperienceRequired: boolean | null;
  location: EventLocation | null;
  topics: Array<string> | null;
  presenters: Array<{
    _id: string;
    name: string | null;
  }> | null;
  resourceCount: number;
}>;

// Source: src/sanity/queries/events.ts
// Variable: EVENT_BY_SLUG_QUERY
// Query: *[_type == "event" && slug.current == $slug][0]{      _id,  title,  "slug": slug.current,  status,  eventType,  startsAt,  endsAt,  summary,  featured,  experienceLevel,  noExperienceRequired,  location,    description,    prerequisites,    setupInstructions,    topics,    registrationUrl,    communityUrl,    recap,    presenters[]->{   _id,  name,  "slug": slug.current,  photo {   asset->{ _id, url, metadata { lqip, dimensions } },  alt,  hotspot,  crop },  shortBio,  githubUrl,  linkedinUrl,  websiteUrl },    // Materials created for this event, plus anything explicitly highlighted.    "resources": array::unique([      ...*[_type == "resource" && event._ref == ^._id]{   _id,  title,  "slug": slug.current,  resourceType,  description,  topics,  experienceLevel,  featured,  externalUrl,  githubUrl,  "fileUrl": file.asset->url,  publishedAt },      ...relatedResources[]->{   _id,  title,  "slug": slug.current,  resourceType,  description,  topics,  experienceLevel,  featured,  externalUrl,  githubUrl,  "fileUrl": file.asset->url,  publishedAt }    ]),    seo {   metaTitle,  metaDescription,  shareImage {   asset->{ _id, url, metadata { lqip, dimensions } },  alt,  hotspot,  crop } }  }
export type EVENT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  status: "cancelled" | "completed" | "scheduled" | null;
  eventType:
    | "career"
    | "hackathon"
    | "meeting"
    | "social"
    | "speaker"
    | "studySession"
    | "workshop"
    | null;
  startsAt: string | null;
  endsAt: string | null;
  summary: string | null;
  featured: boolean | null;
  experienceLevel: "advanced" | "any" | "beginner" | "intermediate" | null;
  noExperienceRequired: boolean | null;
  location: EventLocation | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  prerequisites: Array<string> | null;
  setupInstructions: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  topics: Array<string> | null;
  registrationUrl: string | null;
  communityUrl: string | null;
  recap: string | null;
  presenters: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    photo: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
    shortBio: string | null;
    githubUrl: string | null;
    linkedinUrl: string | null;
    websiteUrl: string | null;
  }> | null;
  resources: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    resourceType:
      | "career"
      | "cheatSheet"
      | "guide"
      | "interviewPrep"
      | "recording"
      | "repository"
      | "slides"
      | "tutorial"
      | "workshop"
      | null;
    description: string | null;
    topics: Array<string> | null;
    experienceLevel: "advanced" | "any" | "beginner" | "intermediate" | null;
    featured: boolean | null;
    externalUrl: string | null;
    githubUrl: string | null;
    fileUrl: string | null;
    publishedAt: string | null;
  }>;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    shareImage: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
  } | null;
} | null;

// Source: src/sanity/queries/events.ts
// Variable: EVENT_SLUGS_QUERY
// Query: *[_type == "event" && defined(slug.current)]{ "slug": slug.current }
export type EVENT_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: src/sanity/queries/opportunities.ts
// Variable: ACTIVE_OPPORTUNITIES_QUERY
// Query: *[_type == "opportunity" && (!defined(deadline) || dateTime(deadline + "T23:59:59Z") >= dateTime(now()))]    | order(featured desc, deadline asc, postedAt desc){        _id,  title,  organization,  opportunityType,  description,  location,  workArrangement,  applicationUrl,  deadline,  postedAt,  skills,  featured    }
export type ACTIVE_OPPORTUNITIES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  organization: string | null;
  opportunityType:
    | "campus"
    | "competition"
    | "fullTime"
    | "hackathon"
    | "internship"
    | "research"
    | "scholarship"
    | null;
  description: string | null;
  location: string | null;
  workArrangement: "hybrid" | "onSite" | "remote" | null;
  applicationUrl: string | null;
  deadline: string | null;
  postedAt: string | null;
  skills: Array<string> | null;
  featured: boolean | null;
}>;

// Source: src/sanity/queries/opportunities.ts
// Variable: ACTIVE_OPPORTUNITIES_BY_TYPE_QUERY
// Query: *[_type == "opportunity" && opportunityType == $opportunityType    && (!defined(deadline) || dateTime(deadline + "T23:59:59Z") >= dateTime(now()))]    | order(deadline asc, postedAt desc){        _id,  title,  organization,  opportunityType,  description,  location,  workArrangement,  applicationUrl,  deadline,  postedAt,  skills,  featured    }
export type ACTIVE_OPPORTUNITIES_BY_TYPE_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  organization: string | null;
  opportunityType:
    | "campus"
    | "competition"
    | "fullTime"
    | "hackathon"
    | "internship"
    | "research"
    | "scholarship"
    | null;
  description: string | null;
  location: string | null;
  workArrangement: "hybrid" | "onSite" | "remote" | null;
  applicationUrl: string | null;
  deadline: string | null;
  postedAt: string | null;
  skills: Array<string> | null;
  featured: boolean | null;
}>;

// Source: src/sanity/queries/people.ts
// Variable: CURRENT_OFFICERS_QUERY
// Query: *[_type == "officerRole" && isCurrent == true] | order(displayOrder asc, position asc){    _id,    position,    term,    person->{   _id,  name,  "slug": slug.current,  photo {   asset->{ _id, url, metadata { lqip, dimensions } },  alt,  hotspot,  crop },  shortBio,  githubUrl,  linkedinUrl,  websiteUrl }  }
export type CURRENT_OFFICERS_QUERY_RESULT = Array<{
  _id: string;
  position: string | null;
  term: string | null;
  person: {
    _id: string;
    name: string | null;
    slug: string | null;
    photo: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
    shortBio: string | null;
    githubUrl: string | null;
    linkedinUrl: string | null;
    websiteUrl: string | null;
  } | null;
}>;

// Source: src/sanity/queries/projects.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"]    | order(        select(          status == "recruiting" => 0,          status == "active" => 1,          status == "testing" => 2,          status == "shipped" => 3,          status == "idea" => 4,          5        ) asc,        featured desc,        coalesce(startedAt, _createdAt) desc      ){        _id,  name,  "slug": slug.current,  status,  shortDescription,  techStack,  experienceLevel,  noExperienceRequired,  featured,  coverImage {   asset->{ _id, url, metadata { lqip, dimensions } },  alt,  hotspot,  crop },  "openRoleCount": count(openRoles),      learningOutcomes,      githubUrl,      currentFocus,      openRoles[]{ _key, title, experienceLevel },      lead->{ _id, name },      mentors[]->{ _id, name }    }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  status:
    | "active"
    | "archived"
    | "idea"
    | "recruiting"
    | "shipped"
    | "testing"
    | null;
  shortDescription: string | null;
  techStack: Array<string> | null;
  experienceLevel: "advanced" | "any" | "beginner" | "intermediate" | null;
  noExperienceRequired: boolean | null;
  featured: boolean | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  openRoleCount: number | null;
  learningOutcomes: Array<string> | null;
  githubUrl: string | null;
  currentFocus: string | null;
  openRoles: Array<{
    _key: string;
    title: string | null;
    experienceLevel: "advanced" | "any" | "beginner" | "intermediate" | null;
  }> | null;
  lead: {
    _id: string;
    name: string | null;
  } | null;
  mentors: Array<{
    _id: string;
    name: string | null;
  }> | null;
}>;

// Source: src/sanity/queries/projects.ts
// Variable: RECRUITING_PROJECTS_QUERY
// Query: *[_type == "project" && status == "recruiting"] | order(featured desc, _createdAt desc){      _id,  name,  "slug": slug.current,  status,  shortDescription,  techStack,  experienceLevel,  noExperienceRequired,  featured,  coverImage {   asset->{ _id, url, metadata { lqip, dimensions } },  alt,  hotspot,  crop },  "openRoleCount": count(openRoles)  }
export type RECRUITING_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  status: "recruiting";
  shortDescription: string | null;
  techStack: Array<string> | null;
  experienceLevel: "advanced" | "any" | "beginner" | "intermediate" | null;
  noExperienceRequired: boolean | null;
  featured: boolean | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  openRoleCount: number | null;
}>;

// Source: src/sanity/queries/projects.ts
// Variable: HOME_PROJECTS_QUERY
// Query: *[_type == "project" && status in ["recruiting", "active"]]    | order(select(status == "recruiting" => 0, 1) asc, featured desc, _createdAt desc)[0...2]{        _id,  name,  "slug": slug.current,  status,  shortDescription,  techStack,  experienceLevel,  noExperienceRequired,  featured,  coverImage {   asset->{ _id, url, metadata { lqip, dimensions } },  alt,  hotspot,  crop },  "openRoleCount": count(openRoles),      learningOutcomes,      githubUrl,      openRoles[]{ _key, title, experienceLevel },      lead->{ _id, name },      mentors[]->{ _id, name }    }
export type HOME_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  status:
    | "active"
    | "archived"
    | "idea"
    | "recruiting"
    | "shipped"
    | "testing"
    | null;
  shortDescription: string | null;
  techStack: Array<string> | null;
  experienceLevel: "advanced" | "any" | "beginner" | "intermediate" | null;
  noExperienceRequired: boolean | null;
  featured: boolean | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  openRoleCount: number | null;
  learningOutcomes: Array<string> | null;
  githubUrl: string | null;
  openRoles: Array<{
    _key: string;
    title: string | null;
    experienceLevel: "advanced" | "any" | "beginner" | "intermediate" | null;
  }> | null;
  lead: {
    _id: string;
    name: string | null;
  } | null;
  mentors: Array<{
    _id: string;
    name: string | null;
  }> | null;
}>;

// Source: src/sanity/queries/projects.ts
// Variable: PROJECT_BY_SLUG_QUERY
// Query: *[_type == "project" && slug.current == $slug][0]{      _id,  name,  "slug": slug.current,  status,  shortDescription,  techStack,  experienceLevel,  noExperienceRequired,  featured,  coverImage {   asset->{ _id, url, metadata { lqip, dimensions } },  alt,  hotspot,  crop },  "openRoleCount": count(openRoles),    description,    screenshots[]{ _key,   asset->{ _id, url, metadata { lqip, dimensions } },  alt,  hotspot,  crop },    learningOutcomes,    openRoles[]{ _key, title, description, experienceLevel, learningOutcome },    githubUrl,    demoUrl,    discussionUrl,    currentFocus,    latestMilestone,    startedAt,    completedAt,    lead->{   _id,  name,  "slug": slug.current,  photo {   asset->{ _id, url, metadata { lqip, dimensions } },  alt,  hotspot,  crop },  shortBio,  githubUrl,  linkedinUrl,  websiteUrl },    mentors[]->{   _id,  name,  "slug": slug.current,  photo {   asset->{ _id, url, metadata { lqip, dimensions } },  alt,  hotspot,  crop },  shortBio,  githubUrl,  linkedinUrl,  websiteUrl },    contributors[]->{ _id, name, githubUrl },    seo {   metaTitle,  metaDescription,  shareImage {   asset->{ _id, url, metadata { lqip, dimensions } },  alt,  hotspot,  crop } }  }
export type PROJECT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: string | null;
  status:
    | "active"
    | "archived"
    | "idea"
    | "recruiting"
    | "shipped"
    | "testing"
    | null;
  shortDescription: string | null;
  techStack: Array<string> | null;
  experienceLevel: "advanced" | "any" | "beginner" | "intermediate" | null;
  noExperienceRequired: boolean | null;
  featured: boolean | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  openRoleCount: number | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  screenshots: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
  learningOutcomes: Array<string> | null;
  openRoles: Array<{
    _key: string;
    title: string | null;
    description: string | null;
    experienceLevel: "advanced" | "any" | "beginner" | "intermediate" | null;
    learningOutcome: string | null;
  }> | null;
  githubUrl: string | null;
  demoUrl: string | null;
  discussionUrl: string | null;
  currentFocus: string | null;
  latestMilestone: string | null;
  startedAt: string | null;
  completedAt: string | null;
  lead: {
    _id: string;
    name: string | null;
    slug: string | null;
    photo: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
    shortBio: string | null;
    githubUrl: string | null;
    linkedinUrl: string | null;
    websiteUrl: string | null;
  } | null;
  mentors: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    photo: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
    shortBio: string | null;
    githubUrl: string | null;
    linkedinUrl: string | null;
    websiteUrl: string | null;
  }> | null;
  contributors: Array<{
    _id: string;
    name: string | null;
    githubUrl: string | null;
  }> | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    shareImage: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
  } | null;
} | null;

// Source: src/sanity/queries/projects.ts
// Variable: PROJECT_SLUGS_QUERY
// Query: *[_type == "project" && defined(slug.current)]{ "slug": slug.current }
export type PROJECT_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: src/sanity/queries/resources.ts
// Variable: RESOURCES_QUERY
// Query: *[_type == "resource"] | order(featured desc, coalesce(publishedAt, _createdAt) desc){      _id,  title,  "slug": slug.current,  resourceType,  description,  topics,  experienceLevel,  featured,  externalUrl,  githubUrl,  "fileUrl": file.asset->url,  publishedAt,    author->{ _id, name },    event->{ _id, title, "slug": slug.current, startsAt }  }
export type RESOURCES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  resourceType:
    | "career"
    | "cheatSheet"
    | "guide"
    | "interviewPrep"
    | "recording"
    | "repository"
    | "slides"
    | "tutorial"
    | "workshop"
    | null;
  description: string | null;
  topics: Array<string> | null;
  experienceLevel: "advanced" | "any" | "beginner" | "intermediate" | null;
  featured: boolean | null;
  externalUrl: string | null;
  githubUrl: string | null;
  fileUrl: string | null;
  publishedAt: string | null;
  author: {
    _id: string;
    name: string | null;
  } | null;
  event: {
    _id: string;
    title: string | null;
    slug: string | null;
    startsAt: string | null;
  } | null;
}>;

// Source: src/sanity/queries/resources.ts
// Variable: RESOURCES_BY_TYPE_QUERY
// Query: *[_type == "resource" && resourceType == $resourceType] | order(publishedAt desc){      _id,  title,  "slug": slug.current,  resourceType,  description,  topics,  experienceLevel,  featured,  externalUrl,  githubUrl,  "fileUrl": file.asset->url,  publishedAt  }
export type RESOURCES_BY_TYPE_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  resourceType:
    | "career"
    | "cheatSheet"
    | "guide"
    | "interviewPrep"
    | "recording"
    | "repository"
    | "slides"
    | "tutorial"
    | "workshop"
    | null;
  description: string | null;
  topics: Array<string> | null;
  experienceLevel: "advanced" | "any" | "beginner" | "intermediate" | null;
  featured: boolean | null;
  externalUrl: string | null;
  githubUrl: string | null;
  fileUrl: string | null;
  publishedAt: string | null;
}>;

// Source: src/sanity/queries/resources.ts
// Variable: RESOURCE_BY_SLUG_QUERY
// Query: *[_type == "resource" && slug.current == $slug][0]{      _id,  title,  "slug": slug.current,  resourceType,  description,  topics,  experienceLevel,  featured,  externalUrl,  githubUrl,  "fileUrl": file.asset->url,  publishedAt,    updatedAt,    "fileName": file.asset->originalFilename,    "fileSize": file.asset->size,    author->{   _id,  name,  "slug": slug.current,  photo {   asset->{ _id, url, metadata { lqip, dimensions } },  alt,  hotspot,  crop },  shortBio,  githubUrl,  linkedinUrl,  websiteUrl },    event->{ _id, title, "slug": slug.current, startsAt },    relatedResources[]->{   _id,  title,  "slug": slug.current,  resourceType,  description,  topics,  experienceLevel,  featured,  externalUrl,  githubUrl,  "fileUrl": file.asset->url,  publishedAt }  }
export type RESOURCE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  resourceType:
    | "career"
    | "cheatSheet"
    | "guide"
    | "interviewPrep"
    | "recording"
    | "repository"
    | "slides"
    | "tutorial"
    | "workshop"
    | null;
  description: string | null;
  topics: Array<string> | null;
  experienceLevel: "advanced" | "any" | "beginner" | "intermediate" | null;
  featured: boolean | null;
  externalUrl: string | null;
  githubUrl: string | null;
  fileUrl: string | null;
  publishedAt: string | null;
  updatedAt: string | null;
  fileName: string | null;
  fileSize: number | null;
  author: {
    _id: string;
    name: string | null;
    slug: string | null;
    photo: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
    shortBio: string | null;
    githubUrl: string | null;
    linkedinUrl: string | null;
    websiteUrl: string | null;
  } | null;
  event: {
    _id: string;
    title: string | null;
    slug: string | null;
    startsAt: string | null;
  } | null;
  relatedResources: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    resourceType:
      | "career"
      | "cheatSheet"
      | "guide"
      | "interviewPrep"
      | "recording"
      | "repository"
      | "slides"
      | "tutorial"
      | "workshop"
      | null;
    description: string | null;
    topics: Array<string> | null;
    experienceLevel: "advanced" | "any" | "beginner" | "intermediate" | null;
    featured: boolean | null;
    externalUrl: string | null;
    githubUrl: string | null;
    fileUrl: string | null;
    publishedAt: string | null;
  }> | null;
} | null;

// Source: src/sanity/queries/resources.ts
// Variable: RESOURCE_SLUGS_QUERY
// Query: *[_type == "resource" && defined(slug.current)]{ "slug": slug.current }
export type RESOURCE_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: src/sanity/queries/siteSettings.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]{    clubName,    shortName,    description,    meetingInfo,    contactEmail,    discordUrl,    githubUrl,    teamsUrl,    footerNote,    socialLinks[]{ _key, platform, label, url },    facultyAdvisor->{      _id,      name,      email,      photo {   asset->{ _id, url, metadata { lqip, dimensions } },  alt,  hotspot,  crop }    },    seo {   metaTitle,  metaDescription,  shareImage {   asset->{ _id, url, metadata { lqip, dimensions } },  alt,  hotspot,  crop } }  }
export type SITE_SETTINGS_QUERY_RESULT = {
  clubName: string | null;
  shortName: string | null;
  description: string | null;
  meetingInfo: string | null;
  contactEmail: string | null;
  discordUrl: string | null;
  githubUrl: string | null;
  teamsUrl: string | null;
  footerNote: string | null;
  socialLinks: Array<{
    _key: string;
    platform:
      | "discord"
      | "github"
      | "instagram"
      | "linkedin"
      | "other"
      | "teams"
      | "youtube"
      | null;
    label: string | null;
    url: string | null;
  }> | null;
  facultyAdvisor: {
    _id: string;
    name: string | null;
    email: string | null;
    photo: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
  } | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    shareImage: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '{\n  "upcomingEvents": count(*[_type == "event" && status == "scheduled"\n    && dateTime(coalesce(endsAt, startsAt)) >= dateTime(now())]),\n  "pastEvents": count(*[_type == "event"\n    && dateTime(coalesce(endsAt, startsAt)) < dateTime(now())]),\n  "activeProjects": count(*[_type == "project" && status in ["recruiting", "active", "testing"]]),\n  "recruitingProjects": count(*[_type == "project" && status == "recruiting"]),\n  "openOpportunities": count(*[_type == "opportunity"\n    && (!defined(deadline) || dateTime(deadline + "T23:59:59Z") >= dateTime(now()))]),\n  "publishedResources": count(*[_type == "resource"]),\n  "people": count(*[_type == "person"])\n}': ADMIN_DASHBOARD_STATS_QUERY_RESULT;
    '\n  *[_type == "event" && status == "scheduled"\n    && dateTime(coalesce(endsAt, startsAt)) >= dateTime(now())]\n    | order(startsAt asc)[0...5]{\n      _id,\n      title,\n      startsAt,\n      endsAt,\n      eventType,\n      location\n    }\n': ADMIN_UPCOMING_EVENTS_QUERY_RESULT;
    '{\n  "eventsMissingSummary": *[_type == "event" && status == "scheduled"\n    && dateTime(coalesce(endsAt, startsAt)) >= dateTime(now())\n    && !defined(summary)]{ _id, title, startsAt },\n  "eventsMissingLocation": *[_type == "event" && status == "scheduled"\n    && dateTime(coalesce(endsAt, startsAt)) >= dateTime(now())\n    && !defined(location.locationType)]{ _id, title, startsAt },\n  "eventsToClose": *[_type == "event" && status == "scheduled"\n    && dateTime(coalesce(endsAt, startsAt)) < dateTime(now())]\n    | order(startsAt desc)[0...5]{ _id, title, startsAt },\n  "opportunitiesClosingSoon": *[_type == "opportunity" && defined(deadline)\n    && dateTime(deadline + "T23:59:59Z") >= dateTime(now())\n    && dateTime(deadline + "T23:59:59Z") <= dateTime(now()) + 60 * 60 * 24 * 7]\n    | order(deadline asc){ _id, title, organization, deadline }\n}': ADMIN_NEEDS_ATTENTION_QUERY_RESULT;
    '\n  *[_type == "event"] | order(startsAt desc){\n    _id,\n    title,\n    "slug": slug.current,\n    status,\n    eventType,\n    startsAt,\n    endsAt,\n    featured,\n    location,\n    "isPast": dateTime(coalesce(endsAt, startsAt)) < dateTime(now()),\n    "resourceCount": count(*[_type == "resource" && event._ref == ^._id]),\n    // count() on a missing array is null, so coalesce for a plain number.\n    "presenterCount": coalesce(count(presenters), 0)\n  }\n': ADMIN_EVENTS_QUERY_RESULT;
    '\n  *[_type == "event" && _id == $id][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    status,\n    eventType,\n    startsAt,\n    endsAt,\n    location,\n    summary,\n    experienceLevel,\n    noExperienceRequired,\n    prerequisites,\n    topics,\n    registrationUrl,\n    communityUrl,\n    recap,\n    featured,\n    "presenterIds": presenters[]._ref,\n    "referenceCount": count(*[references(^._id)])\n  }\n': ADMIN_EVENT_BY_ID_QUERY_RESULT;
    '\n  *[_type == "event" && defined(slug.current) && _id != $excludeId].slug.current\n': EVENT_SLUGS_IN_USE_QUERY_RESULT;
    '\n  *[_type == "person"] | order(name asc){ _id, name }\n': ADMIN_PEOPLE_OPTIONS_QUERY_RESULT;
    '\n  *[_type == "event" && status != "cancelled" && dateTime(coalesce(endsAt, startsAt)) >= dateTime(now())]\n    | order(startsAt asc){\n      \n  _id,\n  title,\n  "slug": slug.current,\n  status,\n  eventType,\n  startsAt,\n  endsAt,\n  summary,\n  featured,\n  experienceLevel,\n  noExperienceRequired,\n  location\n,\n      topics,\n      presenters[]->{ _id, name }\n    }\n': UPCOMING_EVENTS_QUERY_RESULT;
    '\n  *[_type == "event" && status != "cancelled"\n    && dateTime(coalesce(endsAt, startsAt)) < dateTime(now())]\n    | order(startsAt desc){\n      \n  _id,\n  title,\n  "slug": slug.current,\n  status,\n  eventType,\n  startsAt,\n  endsAt,\n  summary,\n  featured,\n  experienceLevel,\n  noExperienceRequired,\n  location\n,\n      topics,\n      presenters[]->{ _id, name },\n      "resourceCount": count(*[_type == "resource" && event._ref == ^._id])\n    }\n': PAST_EVENTS_QUERY_RESULT;
    '\n  *[_type == "event" && slug.current == $slug][0]{\n    \n  _id,\n  title,\n  "slug": slug.current,\n  status,\n  eventType,\n  startsAt,\n  endsAt,\n  summary,\n  featured,\n  experienceLevel,\n  noExperienceRequired,\n  location\n,\n    description,\n    prerequisites,\n    setupInstructions,\n    topics,\n    registrationUrl,\n    communityUrl,\n    recap,\n    presenters[]->{ \n  _id,\n  name,\n  "slug": slug.current,\n  photo { \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  alt,\n  hotspot,\n  crop\n },\n  shortBio,\n  githubUrl,\n  linkedinUrl,\n  websiteUrl\n },\n    // Materials created for this event, plus anything explicitly highlighted.\n    "resources": array::unique([\n      ...*[_type == "resource" && event._ref == ^._id]{ \n  _id,\n  title,\n  "slug": slug.current,\n  resourceType,\n  description,\n  topics,\n  experienceLevel,\n  featured,\n  externalUrl,\n  githubUrl,\n  "fileUrl": file.asset->url,\n  publishedAt\n },\n      ...relatedResources[]->{ \n  _id,\n  title,\n  "slug": slug.current,\n  resourceType,\n  description,\n  topics,\n  experienceLevel,\n  featured,\n  externalUrl,\n  githubUrl,\n  "fileUrl": file.asset->url,\n  publishedAt\n }\n    ]),\n    seo { \n  metaTitle,\n  metaDescription,\n  shareImage { \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  alt,\n  hotspot,\n  crop\n }\n }\n  }\n': EVENT_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "event" && defined(slug.current)]{ "slug": slug.current }\n': EVENT_SLUGS_QUERY_RESULT;
    '\n  *[_type == "opportunity" && (!defined(deadline) || dateTime(deadline + "T23:59:59Z") >= dateTime(now()))]\n    | order(featured desc, deadline asc, postedAt desc){\n      \n  _id,\n  title,\n  organization,\n  opportunityType,\n  description,\n  location,\n  workArrangement,\n  applicationUrl,\n  deadline,\n  postedAt,\n  skills,\n  featured\n\n    }\n': ACTIVE_OPPORTUNITIES_QUERY_RESULT;
    '\n  *[_type == "opportunity" && opportunityType == $opportunityType\n    && (!defined(deadline) || dateTime(deadline + "T23:59:59Z") >= dateTime(now()))]\n    | order(deadline asc, postedAt desc){\n      \n  _id,\n  title,\n  organization,\n  opportunityType,\n  description,\n  location,\n  workArrangement,\n  applicationUrl,\n  deadline,\n  postedAt,\n  skills,\n  featured\n\n    }\n': ACTIVE_OPPORTUNITIES_BY_TYPE_QUERY_RESULT;
    '\n  *[_type == "officerRole" && isCurrent == true] | order(displayOrder asc, position asc){\n    _id,\n    position,\n    term,\n    person->{ \n  _id,\n  name,\n  "slug": slug.current,\n  photo { \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  alt,\n  hotspot,\n  crop\n },\n  shortBio,\n  githubUrl,\n  linkedinUrl,\n  websiteUrl\n }\n  }\n': CURRENT_OFFICERS_QUERY_RESULT;
    '\n  *[_type == "project"]\n    | order(\n        select(\n          status == "recruiting" => 0,\n          status == "active" => 1,\n          status == "testing" => 2,\n          status == "shipped" => 3,\n          status == "idea" => 4,\n          5\n        ) asc,\n        featured desc,\n        coalesce(startedAt, _createdAt) desc\n      ){\n      \n  _id,\n  name,\n  "slug": slug.current,\n  status,\n  shortDescription,\n  techStack,\n  experienceLevel,\n  noExperienceRequired,\n  featured,\n  coverImage { \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  alt,\n  hotspot,\n  crop\n },\n  "openRoleCount": count(openRoles)\n,\n      learningOutcomes,\n      githubUrl,\n      currentFocus,\n      openRoles[]{ _key, title, experienceLevel },\n      lead->{ _id, name },\n      mentors[]->{ _id, name }\n    }\n': PROJECTS_QUERY_RESULT;
    '\n  *[_type == "project" && status == "recruiting"] | order(featured desc, _createdAt desc){\n    \n  _id,\n  name,\n  "slug": slug.current,\n  status,\n  shortDescription,\n  techStack,\n  experienceLevel,\n  noExperienceRequired,\n  featured,\n  coverImage { \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  alt,\n  hotspot,\n  crop\n },\n  "openRoleCount": count(openRoles)\n\n  }\n': RECRUITING_PROJECTS_QUERY_RESULT;
    '\n  *[_type == "project" && status in ["recruiting", "active"]]\n    | order(select(status == "recruiting" => 0, 1) asc, featured desc, _createdAt desc)[0...2]{\n      \n  _id,\n  name,\n  "slug": slug.current,\n  status,\n  shortDescription,\n  techStack,\n  experienceLevel,\n  noExperienceRequired,\n  featured,\n  coverImage { \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  alt,\n  hotspot,\n  crop\n },\n  "openRoleCount": count(openRoles)\n,\n      learningOutcomes,\n      githubUrl,\n      openRoles[]{ _key, title, experienceLevel },\n      lead->{ _id, name },\n      mentors[]->{ _id, name }\n    }\n': HOME_PROJECTS_QUERY_RESULT;
    '\n  *[_type == "project" && slug.current == $slug][0]{\n    \n  _id,\n  name,\n  "slug": slug.current,\n  status,\n  shortDescription,\n  techStack,\n  experienceLevel,\n  noExperienceRequired,\n  featured,\n  coverImage { \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  alt,\n  hotspot,\n  crop\n },\n  "openRoleCount": count(openRoles)\n,\n    description,\n    screenshots[]{ _key, \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  alt,\n  hotspot,\n  crop\n },\n    learningOutcomes,\n    openRoles[]{ _key, title, description, experienceLevel, learningOutcome },\n    githubUrl,\n    demoUrl,\n    discussionUrl,\n    currentFocus,\n    latestMilestone,\n    startedAt,\n    completedAt,\n    lead->{ \n  _id,\n  name,\n  "slug": slug.current,\n  photo { \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  alt,\n  hotspot,\n  crop\n },\n  shortBio,\n  githubUrl,\n  linkedinUrl,\n  websiteUrl\n },\n    mentors[]->{ \n  _id,\n  name,\n  "slug": slug.current,\n  photo { \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  alt,\n  hotspot,\n  crop\n },\n  shortBio,\n  githubUrl,\n  linkedinUrl,\n  websiteUrl\n },\n    contributors[]->{ _id, name, githubUrl },\n    seo { \n  metaTitle,\n  metaDescription,\n  shareImage { \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  alt,\n  hotspot,\n  crop\n }\n }\n  }\n': PROJECT_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "project" && defined(slug.current)]{ "slug": slug.current }\n': PROJECT_SLUGS_QUERY_RESULT;
    '\n  *[_type == "resource"] | order(featured desc, coalesce(publishedAt, _createdAt) desc){\n    \n  _id,\n  title,\n  "slug": slug.current,\n  resourceType,\n  description,\n  topics,\n  experienceLevel,\n  featured,\n  externalUrl,\n  githubUrl,\n  "fileUrl": file.asset->url,\n  publishedAt\n,\n    author->{ _id, name },\n    event->{ _id, title, "slug": slug.current, startsAt }\n  }\n': RESOURCES_QUERY_RESULT;
    '\n  *[_type == "resource" && resourceType == $resourceType] | order(publishedAt desc){\n    \n  _id,\n  title,\n  "slug": slug.current,\n  resourceType,\n  description,\n  topics,\n  experienceLevel,\n  featured,\n  externalUrl,\n  githubUrl,\n  "fileUrl": file.asset->url,\n  publishedAt\n\n  }\n': RESOURCES_BY_TYPE_QUERY_RESULT;
    '\n  *[_type == "resource" && slug.current == $slug][0]{\n    \n  _id,\n  title,\n  "slug": slug.current,\n  resourceType,\n  description,\n  topics,\n  experienceLevel,\n  featured,\n  externalUrl,\n  githubUrl,\n  "fileUrl": file.asset->url,\n  publishedAt\n,\n    updatedAt,\n    "fileName": file.asset->originalFilename,\n    "fileSize": file.asset->size,\n    author->{ \n  _id,\n  name,\n  "slug": slug.current,\n  photo { \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  alt,\n  hotspot,\n  crop\n },\n  shortBio,\n  githubUrl,\n  linkedinUrl,\n  websiteUrl\n },\n    event->{ _id, title, "slug": slug.current, startsAt },\n    relatedResources[]->{ \n  _id,\n  title,\n  "slug": slug.current,\n  resourceType,\n  description,\n  topics,\n  experienceLevel,\n  featured,\n  externalUrl,\n  githubUrl,\n  "fileUrl": file.asset->url,\n  publishedAt\n }\n  }\n': RESOURCE_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "resource" && defined(slug.current)]{ "slug": slug.current }\n': RESOURCE_SLUGS_QUERY_RESULT;
    '\n  *[_type == "siteSettings" && _id == "siteSettings"][0]{\n    clubName,\n    shortName,\n    description,\n    meetingInfo,\n    contactEmail,\n    discordUrl,\n    githubUrl,\n    teamsUrl,\n    footerNote,\n    socialLinks[]{ _key, platform, label, url },\n    facultyAdvisor->{\n      _id,\n      name,\n      email,\n      photo { \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  alt,\n  hotspot,\n  crop\n }\n    },\n    seo { \n  metaTitle,\n  metaDescription,\n  shareImage { \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  alt,\n  hotspot,\n  crop\n }\n }\n  }\n': SITE_SETTINGS_QUERY_RESULT;
  }
}
